---

- name: copy multipath-conf
  become: true
  copy:
    src: multipath.conf
    dest: /etc/multipath.conf

- name: common packages and utility tools install
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ ndvp_packages }}"
  notify:
    - enable and start iscsi services

# create config directory
- name: create config directory
  become: true
  file:
    path: "{{ ndvp_dir }}"
    state: directory
    owner: "{{ docker_user }}"

- name: check docker volume plugin installation
  shell: docker plugin inspect "{{ item.alias }}"
  with_items: "{{ ndvp_plugins }}"
  register: check_plugin
  ignore_errors: yes

- name: install netapp docker volume plugin
  shell: docker plugin install netapp/ndvp-plugin:"{{ item.item.version | default("latest") }}" --alias "{{ item.item.alias }}" --grant-all-permissions --disable
  when: item.rc == 1
  with_items: "{{ check_plugin.results }}"


# copy config file to directory
- name: copy config file
  become: yes
  copy:
    src: "{{ item.item.config_file }}"
    dest: "{{ ndvp_dir }}"
    owner: "{{ docker_user }}"
    group: docker
    mode: 0775
    backup: yes
  when: item.rc == 1
  with_items: "{{ check_plugin.results }}"

- name: set config file path
  shell: docker plugin set "{{ item.item.alias }}" debug="{{ item.item.debug | default("true") }}" config="{{ [ndvp_dir, item.item.config_file] | join("/") }}"
  when: item.rc == 1
  with_items: "{{ check_plugin.results }}"
  notify:
    - enable docker volume plugin
